version: '3'
services:
        web:
                image: gacc-flask-v1
                build: .
                ports:
                        - "8098:8080"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
