version: '3'
services:
        web:
                image: flask_port_v1
                build: .
                ports:
                        - "8098:8098"
                volumes:
                        - ./volumes:/volumes
                restart: unless-stopped
